name: Java CI

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  build:

    name: Maven build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@master
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Build with Maven
        run: mvn package --file pom.xml
      - name: Deploy Javadoc
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.0.3